; supervisor config file

[unix_http_server]
file={{BASEDIR}}/run/supervisor.sock   ; (the path to the socket file)
chmod=0700                       ; sockef file mode (default 0700)


[supervisord]
nodaemon = true
logfile={{BASEDIR}}/weblogs/supervisord.log ; (main log file;default $CWD/supervisord.log)
pidfile={{BASEDIR}}/run/supervisord.pid ; (supervisord pidfile;default supervisord.pid)
childlogdir={{BASEDIR}}/weblogs/            ; ('AUTO' child log dir, default $TEMP)

; the below section must remain in the config file for RPC
; (supervisorctl/web interface) to work, additional interfaces may be
; added by defining them in separate rpcinterface: sections
[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix://{{BASEDIR}}/run/supervisor.sock ; use a unix:// URL  for a unix socket

[program:sshd]
autostart = true
command = /usr/local/bin/startup.sh
priority = 1

[program:fpm]
user = {{WEB_USER}}
autostart = true
command = php-fpm -F
priority = 2

[program:nginx]
user = {{WEB_USER}}
autostart = true
command = nginx -g 'daemon off;'
priority = 3