services:

  django-db:
    image: "docker.io/library/postgres:17-alpine3.22"
    container_name: "django-db"
    hostname: "django-db"
    environment:
      POSTGRES_USER: "${APP_USER}"
      POSTGRES_PASSWORD: "${APP_USER}"
      POSTGRES_HOST_AUTH_METHOD: md5
      DB_NAME: "${DB_NAME}"
    volumes:
      - ./files/sql:/sql
      - ./files/data/fastafiles.md5:/fastafiles.md5
      - ./files/data/django.pgc:/django.pgc
      - ./files/data/django_training.pgc:/django_training.pgc
      - ./files/scripts/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
      - ./files/scripts/init-env.sh:/sql/init-env.sh
networks:
  default:
    name: django