services:

  django-db:
    image: "docker.io/library/postgres:17-alpine3.22"
    container_name: "django-db"
    hostname: "django-db"
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASS}"
      POSTGRES_HOST_AUTH_METHOD: md5
      DB_NAME: "${DB_NAME}"
    volumes:
      - ./files/scripts/sql:/sql
      - ./output:/opt
      - ./files/data/fastafiles.md5:/fastafiles.md5
      - ./files/backups/django.pgc:/django.pgc
      - ./files/backups/django_training.pgc:/django_training.pgc
      - ./files/scripts/shell/export.sh:/export.sh
      - ./files/scripts/shell/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
      - ./files/scripts/shell/init-env.sh:/init-env.sh
networks:
  default:
    name: django