[www]

; Unix user/group of the child processes.
user = {{ WEB_USER }}
group = {{ WEB_GROUP }}

; The address on which to accept FastCGI requests.
listen = {{I5K_PHP_FPM_SOCKET }}


; Permissions for unix socket
listen.owner = {{ WEB_USER }}
listen.group = {{ WEB_GROUP }}
listen.mode = 0660

; List of addresses (IPv4/IPv6) of FastCGI clients which are allowed to connect.
listen.allowed_clients = 127.0.0.1


; Choose how the process manager will control the number of child processes.
pm = dynamic
pm.max_children = 50
pm.start_servers = 5
pm.min_spare_servers = 5
pm.max_spare_servers = 35

; The ping URI to call the monitoring page of FPM. 
ping.path = /ping
ping.response = pong

; The access log file
; Default: not set
access.log = {{ BASEDIR }}/weblogs/$pool.access.log
slowlog = {{ BASEDIR }}/weblogs/$pool.log.slow


; Chdir to this directory at the start.
chdir = {{ DRUPAL }}