---
- name: Requirements Block
  become: true 
  become_user: root
  tags: ["ubuntu","setup"]
  block:

    - name: Install System Packages
      ansible.builtin.apt:
        name: "{{ I5K_SYSTEM_PACKAGES }}"
        state: latest
      changed_when: true
      notify: 
        - stop_services
        - set_postgres_perms
        #- create_drupal_directories

    - name: Signal Services To Stop
      ansible.builtin.meta: flush_handlers


    - name: Enable I5K Related Services
      ansible.builtin.systemd_service:
         name: "{{ item }}"
         enabled: true
         masked: no
      loop: "{{ I5K_SERVICES }}"

    - name: Configure Services
      ansible.builtin.template:
        src: "{{ config.src }}"
        dest: "{{ config.dest }}/{{ config.src }}"
      loop: "{{ I5K_CONFIGS }}"
      loop_control:
        loop_var: config
        label: "{{ config.src }}"

    - name: Link Default Site
      ansible.builtin.file:
        state: link
        src: /etc/nginx/sites-available/default
        path: /etc/nginx/sites-enabled/default
        owner: "{{ WEB_USER }}"
        group: "{{ WEB_GROUP }}"
      
