---
DRUPAL: "{{ BASEDIR|mandatory }}/wwwroot"
DRUPAL_SETTINGS_FILE: "{{ DRUPAL }}/sites/default/settings.php"
DRUPAL_VERSION: 10.4.5
DRUPAL_DIR: "drupal-{{ DRUPAL_VERSION }}"
DRUPAL_FILE: "{{ DRUPAL_DIR }}.tar.gz"
DRUPAL_DOWNLOAD: "https://ftp.drupal.org/files/projects/{{DRUPAL_FILE}}"
DRUPAL_DATA: "{{  lookup('ansible.builtin.env', 'HOME') }}/migrate/data"
DRUPAL_SITE_CONFIGS: "{{ lookup('ansible.builtin.env', 'HOME') }}/migrate/web/configs"
DRUPAL_DBS:
  - "{{ DB_NAME }}"

DRUPAL_DIRECTORIES:
  - "{{ DRUPAL }}"
  - "{{ DRUPAL }}/themes"
  - "{{ DRUPAL }}/modules"
  - "{{ DRUPAL }}/sites/default/files"
  - "{{ BASEDIR }}/data"
  - "{{ BASEDIR }}/data/sync"
  - "{{ BASEDIR }}/run/"

  


DRUPAL_MODULES:
  Drush: drush/drush:^13.3.0
  Bootstrap: drupal/bootstrap:^3.27
  Smtp: drupal/smtp:^1.2
  Sitewide Alerts: drupal/sitewide_alert:^2.2
  Form Options Attributes: drupal/form_options_attributes:^2.1
  Field Group: drupal/field_group:^3.6
  Field Group Table: drupal/field_group_table:^1.1
  DS: drupal/ds:^3.24
  Ext Link: drupal/extlink:^2.0
  Easy Breadcrumbs: drupal/easy_breadcrumb:^2.0
  Search API: drupal/search_api:^1.35
  Rename Admin Path: drupal/rename_admin_paths:^3.0
  Migrate Upgrade: drupal/migrate_upgrade 
  Migrate Plus: drupal/migrate_plus
  Elastic Search API: drupal/elasticsearch_search_api:^2.1.1
  Elastic Search Connector: drupal/elasticsearch_connector:^7.0@alpha
  Facets: drupal/facets:^3.0
  Better Exposed Filters: drupal/better_exposed_filters:^7.0
  Webform: drupal/webform:^6.2.9
  Token: drupal/token:^1.15
  OpenID Connect: drupal/openid_connect_windows_aad
  Captcha: drupal/captcha:^2.0
  
DEFAULT_THEME: i5k
ENABLED_THEMES:
  - bootstrap
  - drupal_base_theme
  - "{{ DEFAULT_THEME }}"

ENABLED_MODULES:
  - extlink
  - easy_breadcrumb
  - filebrowser
  - jquery_ui
  - jquery_ui_draggable
  - jquery_ui_resizable
  - form_options_attributes
  - search_api
  - rename_admin_paths
  - smtp
  - ds
  - field_group
  - field_group_table
  - sitewide_alert
  - migrate
  - migrate_drupal
  - migrate_drupal_ui
  - genomics_workspace
  - elasticsearch_connector
  - elasticsearch_connector_views
  - tripal_layout
  - tripal
  - tripal_chado
  - nal_i5k_tripal_custom_fields
  - nal_i5k_web_apollo
  - webform
  
POETRY_LAYOUT: |
  layout_poetry() {
    if [[ ! -f pyproject.toml ]]; then
      log_error 'No pyproject.toml found.  Use `poetry new` or `poetry init` to create one first.'
      exit 2
    fi

    local VENV=$(dirname $(poetry run which python))
    export VIRTUAL_ENV=$(echo "$VENV" | rev | cut -d'/' -f2- | rev)
    export POETRY_ACTIVE=1
    PATH_add "$VENV"
  }
DRUPAL_SYNC_DIR: |
  $settings['config_sync_directory'] = '{{ BASEDIR }}/data/sync';

DRUPAL_CONNECTION: |
  $databases['default']['default'] = array (
    'database' => '{{ DB_NAME}}',
    'username' => '{{ DB_USER }}',
    'password' => '{{ DB_PASSWORD }}',
    'prefix' => '',
    'host' => '127.0.0.1',
    'port' => 5432,
    'driver' => 'pgsql',
    'namespace' => 'Drupal\\pgsql\\Driver\\Database\\pgsql',
    'autoload' => 'core/modules/pgsql/src/Driver/Database/pgsql/',
  );

MIGRATE: |
  \$databases['migrate']['default'] = array (
    'database' => 'tripal',
    'username' => '{{ DB_USER }}',
    'password' => '{{ DB_USER }}',
    'prefix' => '',
    'host' => '{{DB_HOST}}',
    'port' => '5432',
    'namespace' => 'Drupal\\pgsql\\Driver\\Database\\pgsql',
    'driver' => 'pgsql',
  );

UPDATE_SETTINGS:
    Make settings.php writeable: chmod u+w {{ DRUPAL_SETTINGS_FILE }}
    Add secondary database credentials for the migration: echo "{{MIGRATE}}" >> {{ DRUPAL_SETTINGS_FILE }}
    Make settings.php read-only: chmod u-w {{ DRUPAL_SETTINGS_FILE }} 

WORKSPACE_ACCOUNT_EMAIL: root@localhost
WORKSPACE_ACCOUNT_NAME: root
WORKSPACE_ACCOUNT_PASSWORD: rootPassWord
WORKSPACE_SITE_EMAIL: "{{WORKSPACE_ACCOUNT_EMAIL}}"
WORKSPACE_API_PROTOCOL: http
WORKSPACE_API_URL_PREFIX: api
WORKSPACE_API_PORT: 8000
WORKSPACE_API_URL_PATH: api
WORKSPACE_API_ENDPOINT_VERSION: v1
WORKSPACE_SITE_NAME: "i5k Workspace@NAL"

SITECONFIGS:
  Turn SMTP On: smtp.settings smtp_on true
  Set SMTP Host: "smtp.settings smtp_host {{EMAIL_HOST}}"
  Set SMTP Port: "smtp.settings smtp_port {{EMAIL_PORT}}"
  Configure Site UUID: "system.site uuid {{SITEUUID | mandatory}}"
  Configure Site Default Theme: system.theme default {{ DEFAULT_THEME }}

DRUPAL_INSTALL_COMMAND: |
  ./vendor/bin/drush -q -d -vvv -y site-install standard --db-url="{{WORKSPACE_DB_URL}}" \
            --account-mail="{{ WORKSPACE_ACCOUNT_EMAIL }}" \
            --account-name="{{ WORKSPACE_ACCOUNT_NAME }}" \
            --account-pass="{{ WORKSPACE_ACCOUNT_PASSWORD }}" \
            --site-mail="{{ WORKSPACE_SITE_EMAIL }}" \
            --site-name="{{ WORKSPACE_SITE_NAME }}" \
            --locale="en"

