---

- name: Tripal Setup
  tags: [tripal_setup]
  block:
    - name: "Restore Chado Schema Data"
      community.postgresql.postgresql_db:
        name: "{{ DB_NAME }}"
        state: restore
        target: "{{ BASEDIR }}/web/tripal/chado_for_migrate.sql.gz" 
        login_user: "{{ DB_USER }}"
        login_password: "{{ DB_PASSWORD}}"
      async: 50000
      poll: 1
      register: chado

    - name: Fix Tripal Database
      community.postgresql.postgresql_script:
        db: "{{ DB_NAME }}"
        path: "{{ SCRIPTSDIR }}/d10/sqlfix_database.sql"
        login_user: "{{ DB_USER }}"
        login_password: "{{ DB_PASSWORD}}"
      register: fix
      tags: [sql]

    - name: (Async) Check Chado Terms
      ansible.builtin.shell:
        chdir: "{{ DRUPAL }}"
        cmd: "./vendor/bin/drush trp-check-terms --chado_schema=chado --auto-fix -y"
      async: 50000
      poll: 1
      tags: [drush]

    - name: (Async) Prepare the Chado Instance
      ansible.builtin.shell:
        chdir: "{{ DRUPAL }}"
        cmd: "./vendor/bin/drush trp-prep-chado --schema-name=chado"
      async: 50000
      poll: 1
      tags: [drush]

    - name: Add Chado Schema Name
      ansible.builtin.shell:
        chdir: "{{ DRUPAL }}"
        cmd: "./vendor/bin/drush trp-add-chado --schema-name=chado"
      tags: [drush]

    - name: Set Chado as the Default Schema Name
      ansible.builtin.shell:
        chdir: "{{ DRUPAL }}"
        cmd: "./vendor/bin/drush trp-set-default --schema-name=chado"
      tags: [drush]

  when:
    - wkspdb is defined
    - wkspdb.is_available

- name: Tripal Config
  tags: [tripal_config]
  block:
    - name: (Async) Install General and Genomic content types
      ansible.builtin.shell:
        chdir: "{{ DRUPAL }}"
        cmd: "./vendor/bin/drush trp-import-types --username=root --collection_id={{ item }}"
      loop:
        - general_chado
        - genomic_chado
      loop_control:
        label: "{{ item | regex_replace('_',' ')| title }}"
      async: 50000
      poll: 1
      tags: [drush]

    - name: Execute Database Sql Fixes
      community.postgresql.postgresql_script:
        db: "{{ DB_NAME }}"
        path: "{{ SCRIPTSDIR }}/d10/sql/{{ item }}"
      loop:
        - set_tripal_entity_sequence.sql
        - fix_organism_type.sql
        - fix_analyses_types.sql
        - fix_analysis.sql
      register: fixes
      loop_control:
        label: "{{ item | regex_replace('_|\\.',' ')| title }}"
      notify: drush_clear_cache
      changed_when: fixes['changed']
      tags: [sql]

    - name: (Async) Apply Site Configuration Files
      ansible.builtin.command:
        chdir: "{{ DRUPAL }}"
        cmd: "./vendor/bin/drush cim -y --partial --source={{ BASEDIR }}/web/configs"
      register: configured
      async: 50000
      poll: 1
      tags: [drush]

  when:
    - wkspdb is defined
    - wkspdb.is_available
