---
- name: Start Services
  ansible.builtin.systemd_service:
      name: "{{ item }}"
      state: started
  loop: "{{ I5K_SERVICES }}"
  listen: start_services
  become: true
  ignore_errors: true

- name: Stop Services
  ansible.builtin.systemd_service:
      name: "{{ item }}"
      state: stopped
  loop: "{{ I5K_SERVICES }}"
  listen: stop_services
  become: true
  ignore_errors: true
  

- name: ReStart Services
  ansible.builtin.systemd_service:
      name: "{{ item }}"
      state: restarted
  loop: "{{ I5K_SERVICES }}"
  listen: restart_services
  become: true
  become_user: root

- name: Trust Postgres
  community.postgresql.postgresql_pg_hba:
    dest: /etc/postgresql/16/main/pg_hba.conf
    contype: "{{ item.contype }}"
    users: "{{ item.users }}"
    method: "{{ item.method }}"
    databases: "{{ item.databases }}"
  loop: "{{ POSTGRES_PERMISSIONS}}"
  register: inserted
  listen: set_postgres_perms
  become: true