---
BAD_CONFIGS:
  - cdel -y block.block.garland_block_5
  - cdel -y block.block.garland_system_main
  - cdel -y block.block.garland_system_powered_by
  - cdel -y block.block.garland_user_login
  - cdel -y block.block.i5k_bootstrap_block_10
  - cdel -y block.block.i5k_bootstrap_block_11
  - cdel -y block.block.i5k_bootstrap_block_13
  - cdel -y block.block.i5k_bootstrap_block_2
  - cdel -y block.block.i5k_bootstrap_block_5
  - cdel -y block.block.i5k_bootstrap_block_9
  - cdel -y block.block.i5k_bootstrap_search_form
  - cdel -y block.block.i5k_bootstrap_system_main
  - cdel -y block.block.ohm_block_2
  - cdel -y block.block.ohm_block_5
  - cdel -y block.block.ohm_system_main
  - cdel -y block.block.ohm_system_powered_by
  - cdel -y block.block.ohm_user_login
  - cdel -y block.block.omega_block_10
  - cdel -y block.block.omega_block_2
  - cdel -y block.block.omega_block_5
  - cdel -y block.block.omega_block_6
  - cdel -y block.block.omega_block_9
  - cdel -y block.block.omega_search_form
  - cdel -y block.block.omega_system_main
  - cdel -y block.block.sky_block_2
  - cdel -y block.block.sky_block_3
  - cdel -y block.block.sky_search_form
  - cdel -y block.block.tripal_block_2
  - cdel -y block.block.sky_user_login
  - cdel -y block.block.tripal_system_main
  - cdel -y block.block.tripal_system_powered_by
  - cdel -y block.block.tripal_user_login
  #- cdel -y disable_login.settings
  - cdel -y drupal.settings
  - cdel -y sky.settings
  #- cdel -y tripaldbx.settings

POST_CONFIGS:
  - cdel -y block.block.i5k_content
  - cdel -y block.block.i5k_help
  - cdel -y block.block.i5k_search_form_narrow
  - cdel -y block.block.i5k_account_menu
  - cdel -y block.block.i5k_powered
  - cdel -y block.block.i5k_syndicate
  - cdel -y block.block.i5k_site_branding
  - cdel -y block.block.i5k_block_9
  - cdel -y block.block.i5k_block_10
  - cdel -y block.block.i5k_conditionsofuse
  - cset -y block.block.i5k_views_block__latest_news_block_1 status 0