---
- name: Migration Block
  block:
      - name: Migrate Drupal 7 Data
        ansible.builtin.shell:
          chdir: "{{ DRUPAL }}"
          cmd: ./vendor/bin/drush migrate:upgrade --legacy-db-key=migrate  --legacy-root=/app/i5k-tripal/wwwroot -l https://i5k.nal.isda.gov
        register: migrated
        async: 50000
        poll: 1

      - name: Migration Notification
        ansible.builtin.debug:
          msg: "Content Migration {{ text }}."
        vars:
          text: "{{ migrated['changed'] | ternary('Completed Successfully', 'Failed') }}"
        when: migrated is defined
        notify: delete_d7_configs

      - name: Apply Post Migration Configuration
        ansible.builtin.shell:
          chdir: "{{DRUPAL}}"
          cmd: "./vendor/bin/drush {{ item}}"
        loop: "{{ POST_CONFIGS }}"
        ignore_errors: true

      - name: Remove Organism Image Credit Field
        ansible.builtin.shell:
          chdir: "{{ DRUPAL }}"
          cmd:  ./vendor/bin/drush field:delete tripal_entity organism --field-name=organism_image_credit

      - name: Remove Analysis Alias'
        ansible.builtin.shell:
          cmd: "PGPASSWORD={{ DB_PASSWORD }} psql -U {{ DB_USER }} -h {{ DB_HOST }} {{ DB_NAME }} < {{ input }}"
        vars:
          input: "{{ BASEDIR }}/web/scripts/d10/sql/delete_analysis_alias.sql"
  when: 
    - db is defined
    - db.is_available == true