---

- name: Clear Drupal Cache
  ansible.builtin.shell:
    chdir: "{{DRUPAL}}"
    cmd: "./vendor/bin/drush cr"
  when:
    - db is defined
    - db.is_available == true
  listen: drush_clear_cache

- name: Fix Permissions on Synchronized Files
  ansible.builtin.file:
    path: "{{BASEDIR}}/"
    owner: "{{ WEB_USER }}"
    group: "{{ WEB_GROUP }}"
    recurse: true
    state: directory
  become: true
  become_user: root
  listen: fix_permissions
  changed_when: true
  notify: weblogs

- name: Create Weblogs
  ansible.builtin.file:
    path: /app/weblogs
    state: directory
    group: "{{ WEB_GROUP }}"
    mode: 02770
  become: true
  become_user: root
  listen: weblogs
  
- name: Create Drupal Directories
  ansible.builtin.file:
    path: "{{item}}"
    state: directory
    owner: "{{ WEB_USER  }}"
    group: "{{WEB_GROUP}}"
    mode: 02770
  loop: "{{DRUPAL_DIRECTORIES}}"
  become: true
  become_user: root
  listen: create_drupal_directories

- name: Copy Direnvrc template
  ansible.builtin.template:
    src: direnvrc
    dest: /home/i5k/.direnvrc
  tags: direnv
  listen: copy_direnvrc

- name: Configure Composer
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ BASEDIR }}/"
    owner: "{{ WEB_USER }}"
    group: "{{ WEB_GROUP }}"
  loop:
    - composer.json
    - composer.lock
  listen: configure_composer
  notify: install_requirements
  changed_when: true
  become: true
  become_user: root

- name: Install Requirements from composer.lock 
  ansible.builtin.shell:
    chdir: "{{ BASEDIR }}"
    cmd: "composer install"
  listen: install_requirements
  notify: fix_permissions
  changed_when: true
  become: true 
  become_user: "{{ WEB_USER }}"
  when: "'move' in ansible_run_tags"