---
- name: Configure Service Related Directory Permissions
  ansible.builtin.file:
    path: "{{item}}"
    state: directory
    group: "{{WEB_GROUP}}"
    mode: u=rwx,g=rwx,o=rx
    recurse: true
  loop: "{{ SERVICE_DIRS }}"
  become: true
  become_user: root
  tags: [services]

- name: Create Drupal Directories
  ansible.builtin.file:
    path: "{{item}}"
    state: directory
    owner: "{{WEB_USER}}"
    group: "{{WEB_GROUP}}"
    mode: 02770
  loop: "{{DRUPAL_DIRECTORIES}}"
  become: true
  become_user: root
  tags: [drupal_dirs]

- name: Link Custom Drupal Modules & Themes
  ansible.builtin.file:
    src: "{{ BASEDIR }}/web/{{ item.src }}"
    path: "{{ DRUPAL }}/{{ item.path }}"
    owner: "{{ WEB_USER }}"
    group: "{{ WEB_GROUP }}"
    state: link
  become: true
  become_user: "{{ WEB_USER }}"
  loop:
    - {'src': "themes",  'path': "themes/custom"}
    - {'src': "modules", 'path': "modules/custom"}
    #- {'src': "vendor",  'path': "vendor"}

- name: Configure supervisord
  ansible.builtin.template:
    src: 'templates/supervisord.conf'
    dest: "{{BASEDIR}}/supervisord.conf"
    mode: u=rw,g=r,o=r
  become: true
  become_user: root
  tags: [services]

- name: Configure Services 
  ansible.builtin.template:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
    mode: u=rw,g=r,o=r
    owner: root
    group: root
  loop: "{{ SERVICE_CONFIGS }}"
  become: true
  become_user: root